Repository LeonardoCesca/js-docs, pull requests merged in 2020-02, with the labels that each got.

#4 fix: avatar image
  config/metadata.js
  src/components/contributors/styles.js
Labels: refactore

#7 add: new component - corner
  src/components/corner/index.js
  src/components/corner/styles.js
  src/components/layout/layout.js
Labels: enhancement

#12 Introdução ao map, filter, reduce
  src/components/layout/layout.js
  src/markdown/array-helpers.md
  src/pages/array-helpers/filter-with-map/index.js
  src/pages/array-helpers/index.js
Labels: enhancement

#15 fix: readme PT-BR
  README.md
Labels: documentation, enhancement

#16 feat: change ui
  gatsby-config.js
  package.json
  src/components/contributors/index.js
  src/components/contributors/styles.js
  src/components/footer/styles.js
  src/components/iframes/styles.js
  src/components/layout/layout.js
  src/components/layout/styles.js
  src/pages/index.js
  src/pages/styles.js
  src/theme/globalStyle.js
  src/utils/generateRandomColor.js
  src/utils/generateRandomNumber.js
Labels: enhancement

#2 fix Iframe component
  package-lock.json
  src/components/iframes/index.js
  src/components/iframes/styles.js
Labels: good first issue, refactor

#18 Creating the page about destructuring arrays
  README.md
  config/metadata.js
  src/markdown/destructuring.md
  src/pages/destructuring/destructuring-arrays/index.js
  src/pages/destructuring/index.js
Labels: enhancement

#19 fix: bugs
  README.md
  config/metadata.js
  package.json
  src/components/layout/layout.js
  src/components/layout/styles.js
Labels: bug, enhancement

#21 Add JSON Content
  package-lock.json
  src/components/layout/layout.js
  src/markdown/json.md
  src/pages/json/index.js
Labels: enhancement

#22 Rest parameters
  src/components/layout/layout.js
  src/markdown/rest-params.md
  src/pages/rest-params/index.js
  src/pages/rest-params/undefined-number-of-arguments/index.js
Labels: enhancement
